# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/mael/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="bureau"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    gitfast
    # catimg
    colored-man-pages
    bgnotify
    git-prompt
    fzf
    zsh-syntax-highlighting
    zsh-autosuggestions
    # zsh-vim-mode
    autoswitch_virtualenv
)

export VIRTUAL_ENV_DISABLE_PROMPT=1
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

#PS1="[\$?] $PS1 "

# Shamelessly stolen from afowler theme
local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"
RPS1='${return_code} $(bureau_git_prompt)'


SEP="%{${fg_bold[blue]}%}::%{$reset_color%}"

venv_prompt () {
    if [ -z $VIRTUAL_ENV ];
    then
        echo -n ""
    fi

    echo -n "$(basename "$VIRTUAL_ENV")"
}

ranger_prompt () {
    if [ -n "$RANGER_LEVEL" ];
    then
        echo -n "ranger"
    fi

    echo -n ""
}

sep () {
    if [ -n "$RANGER_LEVEL" ] && [ ! -z "$VIRTUAL_ENV" ];
    then
        echo -n "$SEP"
    fi

    if [ ! -n "$RANGER_LEVEL" ] && [ -z "$VIRTUAL_ENV" ];
    then
        echo -n " "
    fi

    echo -n ""
}

PROMPT='%{${fg_bold[yellow]}%}$(ranger_prompt)%{${reset_color}%}$(sep)%{${fg_bold[magenta]}%}$(venv_prompt)%{${reset_color}%} %{${fg_bold[blue]}%}»%{${reset_color}%} '
#PS1="$VIRTUAL_ENV::$_USERNAME > "

alias zource="source ~/.zshrc"
alias zedit="$EDITOR ~/.zshrc"
alias gdb="gdb -q"

alias pyvenv="python -m venv env"

export MAKEFLAGS=-j4
export OPAMJOBS=4

# Remote neovim
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

# Postgresql
export PGDATA="$HOME/postgres_data"
export PGHOST="/tmp"

# Vim mode config
MODE_CURSOR_VIINS="blinking bar"
MODE_CURSOR_REPLACE="red blinking underline"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="steady underline"
MODE_CURSOR_VISUAL="steady bar"
MODE_CURSOR_VLINE="yellow"

MODE_INDICATOR_VIINS='%F{15}<%F{8}INSERT<%f'
MODE_INDICATOR_VICMD='%F{10}<%F{2}NORMAL<%f'
MODE_INDICATOR_REPLACE='%F{9}<%F{1}REPLACE<%f'
MODE_INDICATOR_SEARCH='%F{13}<%F{5}SEARCH<%f'
MODE_INDICATOR_VISUAL='%F{12}<%F{4}VISUAL<%f'
MODE_INDICATOR_VLINE='%F{12}<%F{4}V-LINE<%f'

#PS1="${MODE_INDICATOR_PROMPT} [\$?] > "

# Autosuggest config
bindkey "^ " autosuggest-execute

# Cargo completion
fpath+=~/.zfunc

# opam configuration
test -r /home/mael/.opam/opam-init/init.zsh && . /home/mael/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.luarocks/bin

export CFLAGS="-Wall -Wextra -pedantic -std=c99"
export CXXFLAGS="-Wall -Wextra -pedantic -std=c++20"

eval $(thefuck --alias)
