#!/bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start polybar
~/.config/polybar/launch.sh

# Start programs if bspwm is loaded for the first time
[ "$1" -eq 0 ] && ~/.config/bspwm/startup.sh


######################
#                    #
#    BSPWM CONFIG    #
#                    #
######################

bspc monitor -d '1' '2' '3' '4' '5' '6'

bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color '#D79921'

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Brave desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
